services:
  postgres:
    image: postgres:latest
    container_name: posternum-db
    restart: always
    environment:
      POSTGRES_DB: posternum_spring_boot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
